### ISSUE TITLE
Trying to edit a Wandering Trader always fails to error

### ISSUE THREAD

**Issue by vico93** [MeowCraftMC/NBTEdit#29]
Hello, NBTEdit Fabric 1.20.4-5.1.0 here!

Basically, when i try to edit the trades of a wandering trader, regardless of putting vanilla or modded items, it always fails.

Here's an excerpt of latest.log when this happens:

```
[23:09:48] [Server thread/WARN]: Exception loading entity: 
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1948) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.method_17839(class_1299.java:555) ~[client-intermediary.jar:?]
	at net.minecraft.class_156.method_17974(class_156.java:515) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:554) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:641) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:592) ~[client-intermediary.jar:?]
	at net.minecraft.class_1299$1.method_31490(class_1299.java:615) ~[client-intermediary.jar:?]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
	at net.minecraft.class_1299$1.tryAdvance(class_1299.java:614) ~[client-intermediary.jar:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5565.method_31731(class_5565.java:76) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:570) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:280) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:785) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2658.<init>(net.minecraft.class_2960, net.minecraft.class_2540)'
	at net.minecraft.class_1309.md4e5328$flycommand$lambda$markNoFallDamage$0$0(class_1309.java:9735) ~[client-intermediary.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.class_1309.markNoFallDamage(class_1309.java:9735) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.handler$cjc001$flycommand$readNbt(class_1309.java:9728) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5749(class_1309.java:806) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5749(class_1308.java:467) ~[client-intermediary.jar:?]
	at net.minecraft.class_1548.method_5749(class_1548.java:124) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1939) ~[client-intermediary.jar:?]
	... 29 more
```

What can be the problem?

**Comment by qyl27** [comment]
What mod have you installed? It seems `md4e5328$flycommand$lambda$markNoFallDamage$0$0` like something mixin added, but not vanilla.

**Comment by qyl27** [comment]
I mean this issue may not be caused by NBTEdit, but by some mod provides the **fly command**.

**Comment by vico93** [comment]
Oh my bad! I will contact the author of the fly command mod i'm using. Thanks for your patience!
